# Generated by Django 5.0.2 on 2025-12-02 07:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxmoxCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('api_url', models.URLField(help_text='Proxmox API URL (e.g., https://192.168.1.100:8006)')),
                ('username', models.CharField(help_text='API username (e.g., root@pam)', max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('verify_ssl', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proxmox Cluster',
                'verbose_name_plural': 'Proxmox Clusters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('cpu_usage', models.FloatField(default=0.0, help_text='CPU usage percentage (0-100)')),
                ('ram_usage', models.FloatField(default=0.0, help_text='RAM usage percentage (0-100)')),
                ('ram_total', models.BigIntegerField(default=0, help_text='Total RAM in bytes')),
                ('ram_used', models.BigIntegerField(default=0, help_text='Used RAM in bytes')),
                ('disk_usage', models.FloatField(default=0.0, help_text='Disk usage percentage (0-100)')),
                ('disk_total', models.BigIntegerField(default=0, help_text='Total disk in bytes')),
                ('disk_used', models.BigIntegerField(default=0, help_text='Used disk in bytes')),
                ('uptime', models.BigIntegerField(default=0, help_text='Uptime in seconds')),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='proxmox_manager.proxmoxcluster')),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
                'ordering': ['cluster', 'name'],
                'unique_together': {('cluster', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vmid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('vm_type', models.CharField(choices=[('qemu', 'VM'), ('lxc', 'Container')], max_length=10)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('paused', 'Paused'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('cpu_cores', models.IntegerField(default=1)),
                ('ram_mb', models.IntegerField(default=512, help_text='RAM in MB')),
                ('disk_gb', models.FloatField(default=0.0, help_text='Disk size in GB')),
                ('cpu_usage', models.FloatField(default=0.0, help_text='CPU usage percentage')),
                ('ram_usage', models.FloatField(default=0.0, help_text='RAM usage percentage')),
                ('uptime', models.BigIntegerField(default=0, help_text='Uptime in seconds')),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_machines', to='proxmox_manager.node')),
            ],
            options={
                'verbose_name': 'Virtual Machine',
                'verbose_name_plural': 'Virtual Machines',
                'ordering': ['node', 'vmid'],
                'unique_together': {('node', 'vmid')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('start', 'Start VM'), ('stop', 'Stop VM'), ('reboot', 'Reboot VM'), ('shutdown', 'Shutdown VM'), ('migrate', 'Migrate VM'), ('snapshot', 'Create Snapshot'), ('rollback', 'Rollback Snapshot'), ('sync', 'Sync Data')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proxmox_manager.proxmoxcluster')),
                ('vm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proxmox_manager.virtualmachine')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
